[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'cd backend && npm install',
  'cd backend && pip install -r requirements.txt',
  'cd frontend && npm install && npm run build'
]

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'node backend/server.js'
