[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[start]
cmd = "python3 service.py & node server.js"
