[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "npm install",
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python3 service.py & node server.js"
